<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="lazyBot">
    <material name="black">
        <color rgba="0.2 0.2 0.2 1." />
    </material>

    <material name="red">
        <color rgba="1.0 0.0 0.0 1.0" />
    </material>

    <material name="blue">
        <color rgba="0.3 0.57 1. 1." />
    </material>

    <!-- Wheel macro -->
    <xacro:macro name="wheel_link" params="name radius length mass">
        <link name="${name}">
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
                <material name="black" />
                <origin rpy="0 0 0" />
            </visual>
            <collision self_collide="false">
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
                <origin rpy="0 0 0" />
                <surface>
                    <friction>
                        <ode>
                            <mu>1.0</mu>
                            <mu2>1.0</mu2>
                        </ode>
                    </friction>
                </surface>
            </collision>
            <inertial>
                <mass value="${mass}" />
                <inertia
                    ixx="${(mass/12)*(3*radius*radius + length*length)}"
                    iyy="${(mass/12)*(3*radius*radius + length*length)}"
                    izz="${(mass/2)*radius*radius}"
                    ixy="0" ixz="0" iyz="0" />
                <origin rpy="0 0 0" />
            </inertial>
        </link>
    </xacro:macro>

    <!-- <link name="base_footprint">

    </link> -->

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

    <link name="chassis">
        <visual>
            <origin xyz="${length/2-len_offs} 0 ${ground_offset+height/2}" />
            <geometry>
                <box size="${length} ${width} ${height}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision self_collide="false">
            <origin xyz="${length/2-len_offs} 0 ${ground_offset+height/2}" />
            <geometry>
                <box size="${length} ${width} ${height}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${length/2-len_offs} 0 ${ground_offset+height/2}" />
            <mass value="${base_mass}" />
            <inertia ixx="${(base_mass/12)*(width*width + height*height)}"
                iyy="${(base_mass/12)*(length*length + height*height)}"
                izz="${(base_mass/12)*(length*length + width*width)}"
                ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <joint name="base_to_back_left_wheel" type="continuous">
        <parent link="chassis" />
        <child link="back_left_wheel" />
        <origin xyz="0 ${wheel_width/2} ${wheel_radius}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <xacro:wheel_link name="back_left_wheel" radius="${wheel_radius}" length="${wheel_length}" mass="${wheel_mass}" />

    <joint name="base_to_back_right_wheel" type="continuous">
        <parent link="chassis" />
        <child link="back_right_wheel" />
        <origin xyz="0 ${-wheel_width/2} ${wheel_radius}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1" />
    </joint>

    <xacro:wheel_link name="back_right_wheel" radius="${wheel_radius}" length="${wheel_length}" mass="${wheel_mass}" />

    <joint name="base_to_front_left_hinge" type="revolute">
        <parent link="chassis" />
        <child link="front_left_hinge" />
        <origin xyz="${wheelbase} ${hinge_d} ${wheel_radius}" />
        <axis xyz="0 0 1" />
        <limit lower="${-pi/4}" upper="${pi/4}" effort="10" velocity="50" />
    </joint>

    <link name="front_left_hinge">
        <inertial>
            <mass value="${hinge_mass}" />
            <inertia ixx="${hinge_mass*0.01}" iyy="${hinge_mass*0.01}" izz="${hinge_mass*0.01}"
                ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

    <joint name="front_left_hinge_to_wheel" type="continuous">
        <parent link="front_left_hinge" />
        <child link="front_left_wheel" />
        <origin xyz="0 ${wheel_width/2 - hinge_d} 0" rpy="${-pi/2} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <xacro:wheel_link name="front_left_wheel" radius="${wheel_radius}" length="${wheel_length}" mass="${wheel_mass}" />

    <joint name="base_to_front_right_hinge" type="revolute">
        <parent link="chassis" />
        <child link="front_right_hinge" />
        <origin xyz="${wheelbase} ${-hinge_d} ${wheel_radius}" />
        <axis xyz="0 0 1" />
        <limit lower="${-pi/4}" upper="${pi/4}" effort="10" velocity="50" />
    </joint>

    <link name="front_right_hinge">
        <inertial>
            <mass value="${hinge_mass}" />
            <inertia ixx="${hinge_mass*0.01}" iyy="${hinge_mass*0.01}" izz="${hinge_mass*0.01}"
                ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

    <joint name="front_right_hinge_to_wheel" type="continuous">
        <parent link="front_right_hinge" />
        <child link="front_right_wheel" />
        <origin xyz="0 ${-wheel_width/2 + hinge_d} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1" />
    </joint>

    <xacro:wheel_link name="front_right_wheel" radius="${wheel_radius}" length="${wheel_length}" mass="${wheel_mass}" />

    <link name="steering_wheel">
        <inertial>
            <mass value="${hinge_mass}" />
            <inertia ixx="${hinge_mass*0.01}" iyy="${hinge_mass*0.01}" izz="${hinge_mass*0.01}"
                ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

    <joint name="steering_joint" type="revolute">
        <parent link="chassis" />
        <child link="steering_wheel" />
        <origin xyz="0 ${length/2} ${height}" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <limit lower="${-pi/2}" upper="${pi/2}" effort="10" velocity="50" />
    </joint>

</robot>